<?php

/**
 * @file
 * Provides Yandex namespace and <item> elements for Views RSS module.
 */

/**
 * Implements hook_views_rss_namespaces().
 */
function views_rss_yandex_views_rss_namespaces() {
  $namespaces['yandex'] = array(
    'prefix' => 'xmlns',
    'uri' => 'http://news.yandex.ru',
  );
  $namespaces['media'] = array(
    'prefix' => 'xmlns',
    'uri' => 'http://search.yahoo.com/mrss/',
  );

  return $namespaces;
}

/**
 * Implements hook_views_rss_item_elements().
 */
function views_rss_yandex_views_rss_item_elements() {
  $elements['yandex:full-text'] = array(
    'description' => t('Full message text for search index.'),
    'help' => 'https://yandex.ru/support/news/export-content/export.html',
  );
  $elements['yandex:genre'] = array(
    'description' => t('Should be either lenta, message, article or interview.'),
    'help' => 'https://yandex.ru/support/news/export-content/export.html',
  );
  $elements['yandex:enclosure'] = array(
    'description' => t('Handles several enclosure elements per item.'),
    'help' => 'https://yandex.ru/support/news/export-content/export.html',
  );
  $elements['yandex:pdalink'] = array(
    'description' => t('Link to the mobile version of the content.'),
    'preprocess functions' => array('views_rss_yandex_preprocess_item_yandex_pdalink'),
    'help' => 'https://yandex.ru/support/news/export-content/export.html',
  );

  return $elements;
}

/**
 * Preprocess function for item <pdalink> element.
 */
function views_rss_yandex_preprocess_item_yandex_pdalink(&$variables) {
  // No value = no preprocessing.
  if (empty($variables['elements'][0]['value'])) {
    return;
  }
  // Change the element key.
  $variables['elements'][0]['key'] = 'pdalink';
}
